build:
  version: "v0.0.2"

support:
  message: "Bienvenidos al sistema bancario (Cuentas) Accenture"
  contactInfo:
    name: "Max Alberto Cuao"
    email: "malbertocuao@gmail.com"
  phoneNumbers:
    - "(57) 3057459906"
    - "(57) 3052610117"
