build:
  version: "v0.0.2"

support:
  message: "Bienvenidos al sistema Cuentas de Accenture - Sistema en Produccion"
  contactInfo:
    name: "Product Owner - Cuentas"
    email: "product.owner@gmail.com"
  phoneNumbers:
    - "(57) 3057459906"
    - "(57) 3052610117"

