server:
  port: 8010

spring:
  application:
    name: "accounts"

#  datasource:
#    url: jdbc:mysql://localhost:3306/accountsdb
#    username: root
#    password: root
#
#  jpa:
#    show-sql: true
#
#  sql:
#    init:
#      mode: always

  datasource:
    url: jdbc:h2:mem:accountsdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Accenture Bank System Accounts"
    version: "1.0.0"
