server:
  port: 8010

spring:
  application:
    name: "accounts"

  datasource:
    url: jdbc:h2:mem:accountsdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true

# Configuración de perfiles por config server
  profiles:
    active: "qa"
  config:
    import: "optional:configserver:http://localhost:8071"

#  Configuración de perfiles por archivo
#  config:
#    import:
#      - "application_qa.yml"
#      - "application_prod.yml"
#  profiles:
#    active:
#      - "default"

build:
  version: "v0.0.2"

support:
  message: "Bienvenidos al sistema bancario (Cuentas) Accenture"
  contactInfo:
    name: "Max Alberto Cuao"
    email: "malbertocuao@gmail.com"
  phoneNumbers:
    - "(57) 3057459906"
    - "(57) 3052610117"

